"""empty message

Revision ID: 5c535f2012d0
Revises: 0209106dfc19
Create Date: 2024-09-14 14:22:31.870593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c535f2012d0'
down_revision = '0209106dfc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pastes_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')
        batch_op.drop_column('file_hash')

    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pastes_timestamp'))

    op.drop_table('pastes')
    # ### end Alembic commands ###
