"""empty message

Revision ID: e9e6694f3855
Revises: 5c535f2012d0
Create Date: 2024-09-14 15:21:03.538496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e6694f3855'
down_revision = '5c535f2012d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.drop_column('disabled')
        batch_op.drop_column('expiry')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('disabled')

    # ### end Alembic commands ###
